package com.java.exception;

import java.io.IOException;

public class Exercise5 {
    public static void main(String [] args){
        try{
            throw new B();

        }catch(A a){

        }catch (B b){

        }
    }
}
